feat: improve function return types
supabase/storage-js pull request #60
Opened 2022-04-06 22:17 UTC by alaister

## What is the current behaviour?

There are some type errors, and functions return everything with `| null`, making it difficult for end-users to work with.

## What is the new behaviour?

Functions now return type unions, which are more correct and easier to work with.

## Additional context

I've labelled this as `feat` instead of `chore` as it should be treated as a **breaking change** because it may show new type errors to existing users.

2022-04-07 00:38 UTC, Jaaneek commented
```ts
  ): Promise<
    | {
        data: { message: string }
        error: null
      }
    | {
        data: null
        error: Error // in future we might add Error || OurOwnError
      }
> {
     const data = something
     return { data, error: null }
    } catch (error) {
        if(basicErrorTypeguard(error)) return { data: null, error }
        // In case we would need to add new Error type in future.
        //if(ourOwnErrorTypeguard(error)) return { data: null, error }
        throw error
    }
  }
  ```


**Reasoning:**
1. If there will be any other error that is not handled by us, we shouldn't return it without a type.
2. User won't be able to handle it, returning an unknown type as error isn't an option as well as that makes developer experience completely worthless. We might as well return a flag 'isError'


**Why this solution:**
Typeguard will ensure that we only ever return our 'Error' and users can handle it.
They will get an error in development that will give them information.
Bonus: 
Backward compatibility.
With this code it's possible to add new ErrorTypes in future without breaking anything. Its maintanable

**Another possible solution (not recommended):**
```ts
catch (error) {
    const castedError = error as Error
      return { data: null, error }
    }
```
This will also work, but it will tell the developer that the error is of type 'Error'.
If any other error is thrown, the developer won't get information about it. This is bug prone.
For example: 
1. Developer shows information from the error to user (user of website).
2. Any other error is thrown that doesn't match 'Error'.
3. Javascript might crash because of accessing a property that doesn't exist.

2022-04-07 00:39 UTC, Jaaneek requested changes
```ts
  ): Promise<
    | {
        data: { message: string }
        error: null
      }
    | {
        data: null
        error: Error // in future we might add Error || OurOwnError
      }
> {
     const data = something
     return { data, error: null }
    } catch (error) {
        if(basicErrorTypeguard(error)) return { data: null, error }
        // In case we would need to add new Error type in future.
        //if(ourOwnErrorTypeguard(error)) return { data: null, error }
        throw error
    }
  }
  ```


**Reasoning:**
1. If there will be any other error that is not handled by us, we shouldn't return it without a type.
2. User won't be able to handle it, returning an unknown type as error isn't an option as well as that makes developer experience completely worthless. We might as well return a flag 'isError'


**Why this solution:**
Typeguard will ensure that we only ever return our 'Error' and users can handle it.
They will get an error in development that will give them information.
Bonus: 
Backward compatibility.
With this code it's possible to add new ErrorTypes in future without breaking anything. Its maintanable

**Another possible solution (not recommended):**
```ts
catch (error) {
    const castedError = error as Error
      return { data: null, error }
    }
```
This will also work, but it will tell the developer that the error is of type 'Error'.
If any other error is thrown, the developer won't get information about it. This is bug prone.
For example: 
1. Developer shows information from the error to user (user of website).
2. Any other error is thrown that doesn't match 'Error'.
3. Javascript might crash because of accessing a property that doesn't exist.

2022-04-07 17:36 UTC, alaister commented
Thanks, @Jaaneek!

I agree with your first option more than the second.

The only thing I don't feel great about is returning an error in the object, but having the function also be able to throw... If a user sees that error in the object, my intuition is that all errors would come through that error and not through a try/catch.

I'm keen to hear your thoughts!

2022-04-07 22:30 UTC, Jaaneek commented
@alaister 

My proposal:

**Create custom error that will format any unknown error**
Something like
```ts
try {
  throw new Error('Some supabase error')
} catch (error) {
  if (error instanceof Error) return error
// if(error instaceof SomeOtherError) return error
// if(error instaceof AnotherError) return error

return toStorageError(error,Reason.Unknown)
}
```


```ts
const toStorageError = (error:unknown,reason:Reason) => {
if(isErrorWithMessage) return new StorageError(error.message,reason,error)


// We might aswell do:
// return new StorageError('',reason,error)
try {
    return new StorageError(JSON.stringify(maybeError),reason,error)
  } catch {
    // fallback in case there's an error stringifying the maybeError
    // like with circular references for example.
    return new StorageError(String(maybeError),reason,error)
  }
}
```

```ts
export class StorageError extends Error {
  reason: Reason
  originalError:unknown
  constructor(message: string, reason: Reason,originalError:unknown) {
    super(message)
    this.name = 'StorageError'
    this.Reason= status
    this.,originalError: originalError
  }


  }
}


```

```ts
enum Reason {
  Unknown,
  OtherEasons...
}
```


```ts
function isErrorWithMessage(error: unknown): error is ErrorWithMessage {
  return (
    typeof error === 'object' &&
    error !== null &&
    'message' in error &&
    typeof (error as Record<string, unknown>).message === 'string'
  )
}
```
**Why?**
It'simportant to let the developer handle the final error.
With introducing 'StorageError' we will let developers always:

- See a message
- We will let him know the reason behind the error (if we know of that)
- Let him handle the final error which will be always unknown.

**Suggestions**
Name it better, 'StorageError ' might be understood as something that we throw, which is not. We are just wrapping it for developers.

**More to read about this pattern**
https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript


I don't have currently much time to analyze that too much so treat everything above as pseudocode.

2022-04-08 15:19 UTC, mirceanton commented
I think that PRs #62 and #63 could also be closed and added  here, as they also address the return types for some functions.

2022-04-08 15:27 UTC, alaister commented
@mirceanton, I'll review your PRs now and try and get them in before this goes out. Thank you!

2022-04-26 04:45 UTC, thebengeu approved these changes

2022-06-16 03:29 UTC, merged

2022-08-04 03:19 UTC, kiwicopple commented
:tada: This PR is included in version 1.8.0-next.1 :tada:

The release is available on:
- [GitHub release](https://github.com/supabase/storage-js/releases/tag/v1.8.0-next.1)
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@supabase/storage-js/v/1.8.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-08-16 13:23 UTC, kiwicopple commented
:tada: This PR is included in version 2.0.0-rc.1 :tada:

The release is available on:
- [GitHub release](https://github.com/supabase/storage-js/releases/tag/v2.0.0-rc.1)
- [npm package (@rc dist-tag)](https://www.npmjs.com/package/@supabase/storage-js/v/2.0.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: